# Generated by Django 5.2 on 2025-12-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#1565C0', help_text='Hex color code (e.g., #1565C0)', max_length=7, verbose_name='Color')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/images/', verbose_name='Image')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (overrides uploaded image if provided)', null=True, verbose_name='Image URL')),
                ('offer_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('EVENT', 'Event'), ('TRAINING', 'Training'), ('MEMBERSHIP', 'Membership'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Offer Type')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('EXPIRED', 'Expired'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Offer')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='Exclusive Offer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
