# Generated by Django 5.2 on 2025-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='average_score',
            field=models.FloatField(default=0.0, verbose_name='Average Score'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0, verbose_name='Games Played'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_won',
            field=models.IntegerField(default=0, verbose_name='Games Won'),
        ),
        migrations.AddField(
            model_name='player',
            name='high_score',
            field=models.IntegerField(default=0, verbose_name='High Score'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_game_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Game Date'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_game_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Game Score'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Total Score'),
        ),
    ]
